server:
  port: 8761 #Spring Cloud - Eureka 기본 서버포트

eureka:
  client:
    register-with-eureka: false #Cluster 환경에서 본인의 서버 주소를 다른 서버에게 알리기 위함, 단일 서버에서는 false
    fetch-registry: false #메모리에 올려진 레지스트리 목록을 주기적으로 갱신, 본 환경에서는 false

spring:
  application:
    name: msa-init
#  datasource:
#    url: jdbc:postgresql://localhost:5432/root
#    driver-class-name: org.postgresql.Driver
#    username: root
#    password: 1234
  jpa:
    show-sql: true #SQL 실행문 로그로 기록
    properties:
      hibernate:
        format_sql: true #pretty format
        highlight_sql : true #colored
  data:
#    mongodb:
#      database: cyberops
#    redis:
#      host: localhost
#      port: 6379

logging:
  level:
    org.springframework.batch.item.database: DEBUG
